<!--====== Jquery js ======-->
<script src="{{ asset('assets/js/plugins/jquery-3.7.1.min.js') }}"></script>
<!--====== Bootstrap js ======-->
<script src="{{ asset('assets/js/plugins/popper.min.js') }}"></script>
<!--====== Bootstrap js ======-->
<script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
<!--====== Gsap Js ======-->
<script src="{{ asset('assets/js/plugins/gsap/gsap.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/gsap/SplitText.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/gsap/ScrollSmoother.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/gsap/ScrollTrigger.min.js') }}"></script>
<!--====== Slick js ======-->
<script src="{{ asset('assets/js/plugins/slick.min.js') }}"></script>
<!--====== Magnific js ======-->
<script src="{{ asset('assets/js/plugins/jquery.magnific-popup.min.js') }}"></script>
<!--====== Waypoint js ======-->
<script src="{{ asset('assets/js/plugins/jquery.waypoints.js') }}"></script>
<!--====== CounterUp js ======-->
<script src="{{ asset('assets/js/plugins/jquery.counterup.min.js') }}"></script>
<!--====== Aos js ======-->
<script src="{{ asset('assets/js/plugins/aos.js') }}"></script>
<!--====== Common js ======-->
<script src="{{ asset('assets/js/theme.js') }}"></script>
